# Generated by Django 3.2.6 on 2021-08-27 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symbol',
            name='dimension',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='index',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='size',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
