# Generated by Django 3.2.6 on 2021-08-27 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20210827_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symbol',
            name='type',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
